In [1]:
import numpy as np

In [ ]:
#syntax for array creation

var_name= np.array([1,2,3,'abcd'])
var_name

array(['1', '2', '3', 'abcd'], dtype='<U21')

In [ ]:
#upcasting
#var_name= np.array([1,2.2,3])
#var_name

array([1. , 2.2, 3. ])

In [ ]:
#vectorization
'''arr= np.array([1,2,3])
arr+1
arr-1
arr*2
arr//2
arr/2
arr**2
arr%2'''

array([2, 3, 4])

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2


array([5, 7, 9])

In [ ]:
#properties
d1 =np.array([1,2,3])
d1.dtype

d1.shape
d1.ndim
d1.size

3

In [ ]:


d4=np.array([
    [[[1,2,3],[4,5,6]]],
    [[[7,8,9],[10,12,13]]]
])
d4.shape



(2, 1, 2, 3)

In [ ]:
d1=np.array([1,2,3])

d1.shape


(3,)

In [ ]:
d2=np.array([[1,2,3],
             [3,4,5]])
d2.shape


(2, 3)

In [3]:
d3=np.array([
    [[1,2,3],[4,5,6]],
    [[6,7,8],[10,12,13]]
])
d3.shape

(2, 2, 3)

In [4]:
d4=np.array([[[[1,2,3]],[[2,3,4]]]])
d4.shape

(1, 2, 1, 3)

In [ ]:

# broadcasting


In [2]:
#slicing

#d2[1][0:2:1]
d2=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
d2[:,2]
d2[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d3



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [10, 12, 13]]])

In [ ]:
d3[::-1]

array([], shape=(0, 2, 3), dtype=int64)

In [ ]:
ar=np.array(np.arange(1,11,0.5))
ar

np.zeros((3,3,3))

np.ones((3,3))
np.full((3,4),5)
np.linspace(1,10,5)
np.eye(4)
np.random.rand(3,3)
np.random.randint(1,10,(3,3))

#statistical
np.mean(d1)
np.sum(d1)
np.var(d1)
np.std(d1)
np.median(d1)
np.average(d1)
#np.mode
np.empty(5)

t=np.arrange(1,7)

t.reshape(2,3)

TypeError: reshape() missing 1 required positional argument: 'newshape'

In [26]:
np.empty((2,2))



array([[4.09888478e-315, 0.00000000e+000],
       [3.98851623e-315, 6.88557423e-310]])

In [18]:
import re as r
x = r.findall("\d","a1b2c3")




['1', '2', '3']


<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-3021311802.py:2: SyntaxWarning: invalid escape sequence '\d'
  x = r.findall("\d","a1b2c3")


In [32]:
a=[1,2,3]
b=a
b.append(4)
a

[1, 2, 3, 4]

In [38]:
d={'a':1,'b':2}
d.get('b',5)


2